libp2p:
  # Unspecified identityPath results in random peer identity generation.
  # identityPath: '<path-to-identity-key>'
  listenAddr:
    - /ip4/0.0.0.0/tcp/40090
    - /ip4/0.0.0.0/udp/40090/quic
    - /ip4/0.0.0.0/udp/40090/quic-v1
  userAgent: ipni/cassette
  # To disable the connection manger set `connManager` to `null`.
  connManager:
    lowWater: 500
    highWater: 5000
    gracePeriod: 20s
    silencePeriod: 10s
    emergencyTrim: true
  # Disable resource manager by setting it to null
  # To enable default resource manger, set the value to non-nil, e.g. {}
  resourceManager: null
ipni:
  httpListenAddr: 0.0.0.0:40080
  httpAllowOrigin: '*'
  preferJsonResponse: false
  cascadeLabel: legacy
  requireCascadeQueryParam: false
  responseTimeout: 5s
  findByMultihash: true
  disableAddrFilter: false
metrics:
  listenAddr: 0.0.0.0:40081
  enablePprofDebug: true
bitswap:
  peers:
    # Example static addrs.
    - '/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN'
    - '/dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa'
    - '/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb'
    - '/dnsaddr/bootstrap.libp2p.io/p2p/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt'
    # Example dynamic addrs auto discovered by lookup over IPFS DHT.
    - '/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ'
  maxBroadcastBatchSize: 100
  maxBroadcastBatchWait: 100ms
  fallbackOnWantBlock: true
  recipientsRefreshInterval: 10s
  sendChannelBuffer: 100
  peerDiscoveryInterval: 10s
  peerDiscoveryAddrTTL: 10m
  recipientCBTripFunc:
    consecutiveFailures: 10
  recipientCBCounterResetInterval: 10s
  recipientCBFailOnContextCancel: false
  recipientCBFailOnContextDeadline: true
  recipientCBHalfOpenMaxSuccesses: 10
  recipientCBOpenTimeout: 1s
  recipientCBOpenTimeoutBackOff:
    exponential: { }
  recipientSendTimeout: 5s
  broadcastCancelAfter: 5s
  receiverChannelBuffer: 100